apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: self-heal-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
