schedule: "*/10 * * * *"

image:
  repository: python
  tag: 3.11-slim

config:
  RETRY_COUNT: "3"
  RETRY_INTERVAL: "10"
  COOLDOWN_PERIOD: "7200"
  DISK_THRESHOLD: "75"

  LOG_DIR: "/opt/logs"

  EMAIL_ENABLED: "true"
  EMAIL_SUBJECT_PREFIX: "[Self-Heal][Disk]"
  EMAIL_FROM: "qa_emplay@emplay.net"
  EMAIL_TO: "nandhini.s@emplay.net,navya.sri@emplay.net"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "qa_emplay@emplay.net"

secrets:
  SMTP_PASSWORD: ""   # set during helm install

persistence:
  state:
    size: 5Mi

# Shared logs PVC (recommended: created ONE TIME outside helm)
sharedLogsPVC:
  enabled: false
  name: "self-heal-logs-pvc"
  size: 100Mi
  storageClassName: "standard"

debugger:
  image: "ubuntu:24.04"
  sleepSeconds: 120
